function Espanhol(){
    const paragrafos = document.querySelectorAll("p a")
    paragrafos[0].textContent = " El Teatro Prezewodowski es uno de los más antiguos de América Latina, su primera piedra fue colocada en 1883 y fue inaugurado en 1886. El edificio está catalogado como patrimonio histórico por el Instituto do Patrimônio Histórico e Artístico do Estado (IPHAE).Durante décadas, el teatro sirvió de escenario para presentaciones de compañas artísticas nacionales y internacionales y para eventos sociales locales. Durante la Segunda Guerra Mundial, las actividades bajaron y el lugar pasó a funcionar como cine, entrando en decadencia y cerró definitivamente en 1964. Habiendo permanecido abandonado durante muchos años, su recuperación concluyó en 1992."
    paragrafos[1].textContent = "El nombre del teatro rinde homenaje al capitán de corbeta de la Armada Brasileña Estanislau Prezewodowski, que participó en la Guerra del Paraguay y prestó servicio en el municipio entre 1872 y 1874. La característica más impresionante del teatro en la epoca de su construcción era la platea móvil, diseñada para nivelar el suelo con el escenario, ya que el lugar también celebraba bailes. El mecanismo de elevación ya no existe. Otra característica unica es el canal de agua situado debajo del escenario, que llos arquitectos de la época creían que mejoraría la acústica del edificio."
    paragrafos[2].textContent = "Durante muchos años, el Teatro Prezewodowski acogió a compañías líricas de renombre internacional que seguían la ruta Río de Janeiro – São Paulo – Porto Alegre – Buenos Aires – Montevideo, con una escala obligada en Itaqui —uno de los centros culturales de la época—, además de presentar a reconocidos artistas del Teatro Nacional. El Teatro Prezewodowski es de suma importancia para toda la comunidad de Itaqui y mantiene una agenda repleta de eventos, como obras de teatro, ballets, espectáculos musicales, conferencias, seminarios, etc. El teatro recibe cerca de 1000 visitantes al año y tiene capacidad para 218 personas."
    paragrafos[3].textContent = "Horario de Atención de la Secretaria Municipal de Esporte, Cultura, Lazer e Turismo(SMECULT): De lunes a viernes, de 7:00 a 13:00 horas. La entrada de la secretaría queda a la derecha del teatro. "
}
function English(){
    const paragrafos = document.querySelectorAll("p a")
    paragrafos[0].textContent = ""
    paragrafos[1].textContent = ""
    paragrafos[2].textContent = ""
    paragrafos[3].textContent = ""
}
function Portuguese(){
    const paragrafos = document.querySelectorAll("p a")
    paragrafos[0].textContent = "O Teatro (grafia original: Theatro) Prezewodowski é um dos mais antigos teatros da América Latina, com sua pedra fundamental lançada em 1883 e sua inauguração em 1886. É um prédio tombado pelo Instituto do Patrimônio Histórico e Artístico do Estado (IPHAE). Durante décadas o teatro serviu de palco para apresentações de campanhas artísticas nacionais e internacionais e acontecimentos sociais locais. Durante a Segunda Guerra as atividades diminuíram. A casa passou a funcionar como cinema, entrando em decadência e sendo fechada, definitivamente, em 1964. Tendo permanecido abandonado por muitos anos, sua recuperação foi concluída em 1992."
    paragrafos[1].textContent = "O nome do teatro é uma homenagem ao capitão-tenente da Marinha Brasileira Estanislau Prezewodowski, que participou da Guerra do Paraguai e serviu no município entre 1872-74. A característica mais impressionante da construção do Teatro, na época de sua construção, era a plateia móvel, com a finalidade de nivelar esta parte do palco, pois neste local também eram realizados bailes. Infelizmente, o mecanismo de elevação não existe mais. Outra característica única é a vertente de água abaixo do palco, que os arquitetos da época acreditavam que aprimoraria a acústica do prédio. "
    paragrafos[2].textContent = "Por muitos anos, além da apresentação de conhecidos artistas do Teatro Nacional, o Theatro Prezewodowski abrigou companhias líricas de renome internacional, que traçavam seu roteiro Rio de Janeiro – São Paulo – Porto Alegre – Buenos Aires – Montevidéu, com escala obrigatória em Itaqui, um dos centros culturais da épocal. O Teatro Prezewodowski é de suma importância para toda comunidade itaquiense e mantém uma agenda de eventos repleta, como espetáculos de teatro, balés, eventos musicais, palestras, seminários, etc. O Teatro recebe cerca de 1000 visitantes por ano e tem capacidade para 218 pessoas."
    paragrafos[3].textContent = "Atendimento - Secretaria Municipal de Esporte, Cultura, Lazer e Turismo (SMECULT): De segunda a sexta-feira, das 7h às 13h. A secretaria fica no acesso à direita do teatro."
}